### ISSUE TITLE
No longer plays video after recent update

### ISSUE THREAD

**Issue by mysteryx93** [smplayer-dev/smplayer#402]
SMPlayer had been working fine until a recent update. There's been some update to Plasma, some updates to NVidia... not sure exactly where it broke.

Now when I play videos, it plays as if it was audio-only. If I check "run MPV in its own window", then it works. It only fails to show the video when playing embedded.

What additional information do you need to diagnose?

I have SMPlayer 22.2.0-1

inzi -Faz
```
System:
Kernel: 5.16.12-zen1-1-zen x86_64 bits: 64 compiler: gcc v: 11.2.0
parameters: BOOT_IMAGE=/@/boot/vmlinuz-linux-zen
root=UUID=58203bda-e2e2-4c32-a006-c91d933cad4e rw rootflags=subvol=@
quiet splash rd.udev.log_priority=3 vt.global_cursor_default=0
systemd.unified_cgroup_hierarchy=1 loglevel=3 intel_iommu=on
nvidia-drm.modeset=1
Desktop: KDE Plasma 5.24.2 tk: Qt 5.15.3 info: latte-dock wm: kwin_x11
vt: 1 dm: SDDM Distro: Garuda Linux base: Arch Linux
Machine:
Type: Laptop System: Acer product: Predator PH315-53 v: V1.01
serial: <superuser required>
Mobo: CML model: QX50_CMS v: V1.01 serial: <superuser required>
UEFI: Insyde v: 1.01 date: 04/27/2020
Battery:
ID-1: BAT1 charge: 42.3 Wh (100.0%) condition: 42.3/58.8 Wh (72.0%)
volts: 16.5 min: 15.4 model: SMP AP18E7M type: Li-ion serial: <filter>
status: Full
Device-1: nintendo_switch_controller_battery_0003:057E:2009.0001
model: N/A serial: N/A charge: Full status: Full
CPU:
Info: model: Intel Core i7-10750H bits: 64 type: MT MCP arch: Comet Lake
family: 6 model-id: 0xA5 (165) stepping: 2 microcode: 0xEC
Topology: cpus: 1x cores: 6 tpc: 2 threads: 12 smt: enabled cache:
L1: 384 KiB desc: d-6x32 KiB; i-6x32 KiB L2: 1.5 MiB desc: 6x256 KiB
L3: 12 MiB desc: 1x12 MiB
Speed (MHz): avg: 4575 high: 4928 min/max: 800/5000 scaling:
driver: intel_pstate governor: performance cores: 1: 4923 2: 4800 3: 4801
4: 4800 5: 1901 6: 4803 7: 4928 8: 4801 9: 4800 10: 4804 11: 4747
12: 4800 bogomips: 62399
Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Vulnerabilities:
Type: itlb_multihit status: KVM: VMX disabled
Type: l1tf status: Not affected
Type: mds status: Not affected
Type: meltdown status: Not affected
Type: spec_store_bypass
mitigation: Speculative Store Bypass disabled via prctl
Type: spectre_v1
mitigation: usercopy/swapgs barriers and __user pointer sanitization
Type: spectre_v2
mitigation: Enhanced IBRS, IBPB: conditional, RSB filling
Type: srbds status: Not affected
Type: tsx_async_abort status: Not affected
Graphics:
Device-1: Intel CometLake-H GT2 [UHD Graphics]
vendor: Acer Incorporated ALI driver: i915 v: kernel ports: active: none
off: eDP-1 empty: HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:9bc4
class-ID: 0300
Device-2: NVIDIA TU106M [GeForce RTX 2060 Mobile]
vendor: Acer Incorporated ALI driver: nvidia v: 510.54
alternate: nouveau,nvidia_drm pcie: gen: 3 speed: 8 GT/s lanes: 16 ports:
active: none off: HDMI-A-2 empty: DP-1 bus-ID: 01:00.0 chip-ID: 10de:1f15
class-ID: 0300
Device-3: Quanta HD User Facing type: USB driver: uvcvideo bus-ID: 1-5:5
chip-ID: 0408:a061 class-ID: 0e02
Display: x11 server: X.Org v: 1.21.1.3 compositor: kwin_x11 driver: X:
loaded: modesetting,nvidia gpu: i915,nvidia display-ID: :0 screens: 1
Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.0x11.2")
s-diag: 582mm (22.9")
Monitor-1: HDMI-0 res: 1920x1080 hz: 60 dpi: 40
size: 1210x680mm (47.6x26.8") diag: 1388mm (54.6")
OpenGL: renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
v: 4.6.0 NVIDIA 510.54 direct render: Yes
Audio:
Device-1: Intel Comet Lake PCH cAVS vendor: Acer Incorporated ALI
driver: snd_hda_intel v: kernel
alternate: snd_soc_skl,snd_sof_pci_intel_cnl bus-ID: 00:1f.3
chip-ID: 8086:06c8 class-ID: 0403
Device-2: NVIDIA TU106 High Definition Audio
vendor: Acer Incorporated ALI driver: snd_hda_intel v: kernel pcie: gen: 3
speed: 8 GT/s lanes: 16 bus-ID: 01:00.1 chip-ID: 10de:10f9 class-ID: 0403
Device-3: Texas Instruments PCM2900B Audio CODEC type: USB
driver: hid-generic,snd-usb-audio,usbhid bus-ID: 1-1.3:6 chip-ID: 08bb:29b0
class-ID: 0300
Sound Server-1: ALSA v: k5.16.12-zen1-1-zen running: yes
Sound Server-2: PulseAudio v: 15.0 running: no
Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
Device-1: Intel Comet Lake PCH CNVi WiFi vendor: Rivet Networks
driver: iwlwifi v: kernel bus-ID: 00:14.3 chip-ID: 8086:06f0 class-ID: 0280
IF: wlp0s20f3 state: up mac: <filter>
Device-2: Realtek vendor: Acer Incorporated ALI driver: r8169 v: kernel
pcie: gen: 1 speed: 2.5 GT/s lanes: 1 port: 3000 bus-ID: 07:00.0
chip-ID: 10ec:2600 class-ID: 0200
IF: enp7s0 state: down mac: <filter>
IF-ID-1: anbox0 state: down mac: <filter>
IF-ID-2: virbr0 state: down mac: <filter>
IF-ID-3: virbr1 state: down mac: <filter>
Bluetooth:
Device-1: Intel AX201 Bluetooth type: USB driver: btusb v: 0.8
bus-ID: 1-14:7 chip-ID: 8087:0026 class-ID: e001
Report: bt-adapter ID: hci0 rfk-id: 1 state: down
bt-service: enabled,running rfk-block: hardware: no software: yes
address: <filter>
Drives:
Local Storage: total: 5.26 TiB used: 1.06 TiB (20.1%)
SMART Message: Unable to run smartctl. Root privileges required.
ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Western Digital
model: PC SN730 SDBQNTY-512G-1014 size: 476.94 GiB block-size:
physical: 512 B logical: 512 B speed: 31.6 Gb/s lanes: 4 type: SSD
serial: <filter> rev: 11101100 temp: 24.9 C scheme: GPT
ID-2: /dev/sda maj-min: 8:0 vendor: HGST (Hitachi) model: HTS721010A9E630
size: 931.51 GiB block-size: physical: 4096 B logical: 512 B
speed: 6.0 Gb/s type: HDD rpm: 7200 serial: <filter> rev: A3J0
scheme: GPT
ID-3: /dev/sdb maj-min: 8:16 vendor: Crucial model: CT275MX300SSD4
size: 256.17 GiB block-size: physical: 512 B logical: 512 B speed: 6.0 Gb/s
type: SSD serial: <filter> rev: R060 scheme: GPT
ID-4: /dev/sdc maj-min: 8:32 type: USB vendor: Western Digital
model: WD Elements 2620 size: 3.64 TiB block-size: physical: 4096 B
logical: 512 B type: N/A serial: <filter> rev: 1023 scheme: GPT
Partition:
ID-1: / raw-size: 468.84 GiB size: 468.84 GiB (100.00%)
used: 216.81 GiB (46.2%) fs: btrfs dev: /dev/nvme0n1p5 maj-min: 259:3
ID-2: /boot/efi raw-size: 100 MiB size: 96 MiB (96.00%)
used: 51.2 MiB (53.4%) fs: vfat dev: /dev/nvme0n1p1 maj-min: 259:1
ID-3: /home raw-size: 468.84 GiB size: 468.84 GiB (100.00%)
used: 216.81 GiB (46.2%) fs: btrfs dev: /dev/nvme0n1p5 maj-min: 259:3
ID-4: /var/log raw-size: 468.84 GiB size: 468.84 GiB (100.00%)
used: 216.81 GiB (46.2%) fs: btrfs dev: /dev/nvme0n1p5 maj-min: 259:3
ID-5: /var/tmp raw-size: 468.84 GiB size: 468.84 GiB (100.00%)
used: 216.81 GiB (46.2%) fs: btrfs dev: /dev/nvme0n1p5 maj-min: 259:3
Swap:
Kernel: swappiness: 133 (default 60) cache-pressure: 100 (default)
ID-1: swap-1 type: zram size: 15.46 GiB used: 2.8 MiB (0.0%)
priority: 100 dev: /dev/zram0
Sensors:
System Temperatures: cpu: 55.0 C pch: 65.0 C mobo: N/A gpu: nvidia
temp: 48 C
Fan Speeds (RPM): N/A
Info:
Processes: 377 Uptime: 12m wakeups: 2 Memory: 15.46 GiB
used: 3.56 GiB (23.0%) Init: systemd v: 250 tool: systemctl Compilers:
gcc: 11.2.0 clang: 13.0.1 Packages: pacman: 1812 lib: 501 Shell: fish
v: 3.3.1 default: Bash v: 5.1.16 running-in: konsole inxi: 3.3.13
```

**Comment by smplayer-dev** [comment]
> What additional information do you need to diagnose?

The mpv/mplayer log when playing a file (menu View)

**Comment by mysteryx93** [comment]
```
/usr/bin/mpv --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-161db --msg-level=ffmpeg/demuxer=error --video-rotate=no --no-fs --hwdec=no --sub-auto=fuzzy --vo=gpu, --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=106954769 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=110 --cache=auto --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/home/hanuman/Pictures/smplayer_screenshots --audio-pitch-correction=yes --volume-max=110 --hr-seek-framedrop=no --profile=gpu-hq --gpu-api=vulkan --hwdec=auto-copy --vulkan-async-compute=yes --vulkan-async-transfer=yes --vulkan-queue-count=1 --autofit=85%x85% --dither=error-diffusion --deband=yes --deband-iterations=2 --deband-threshold=20 --deband-range=16 --scale=ewa_hanning --scale-radius=3.2383154841662362 --cscale=ewa_lanczossoft --dscale=mitchell --scale-antiring=0 --cscale-antiring=0 --correct-downscaling=yes --linear-downscaling=no --sigmoid-upscaling=yes --blend-subtitles=no --hdr-compute-peak=yes --tone-mapping=mobius --glsl-shaders-clr --fbo-format=rgba16f --glsl-shader=~/.config/mpv/shaders/FSRCNN_x2_r2_32-0-2.glsl --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} /run/media/hanuman/Storage/NaturalGrounding/Girls' Generation/Divine.mkv

  autoload: Prepending Dear Santa.mkv 
  autoload: Prepending Dear Mom.mkv 
  autoload: Prepending Day By Day.mp4 
  autoload: Prepending Dancing Queen.mp4 
  autoload: Prepending Cooky.mkv 
  autoload: Prepending Chocolate Love.mkv 
  autoload: Prepending Chocolate Love Live.mp4 
  autoload: Prepending Catch Me If You Can.mp4 
  autoload: Prepending Born To Be A Lady (Live).mkv 
  autoload: Prepending Born To Be A Lady (2011 Japan Tour).mp4 
  autoload: Prepending Beginning (Live).mp4 
  autoload: Prepending Beep Beep.mp4 
  autoload: Prepending Beep Beep Live.mp4 
  autoload: Prepending All My Love Is For You.mp4 
  autoload: Prepending Adrenaline (KBS Music Bank).mkv 
  autoload: Adding Domino's Pizza Dance.mp4 
  autoload: Adding Echo.mkv 
  autoload: Adding Flower Power.mp4 
  autoload: Adding Gee (Alikstae Mix).mp4 
  autoload: Adding Gee (Japan Version).mp4 
  autoload: Adding Gee (Live 090214).avi 
  autoload: Adding Gee.mp4 
  autoload: Adding Gee (Show Music Core 20150912).mkv 
  autoload: Adding Geeurlove.mp4 
  autoload: Adding Genie (Japanese Ver).mp4 
  autoload: Adding Genie (Live 090704).mp4 
  autoload: Adding Genie (Samsung 3D).mp4 
  autoload: Adding Ha Ha Ha.mkv 
  autoload: Adding Holler.mp4 
  autoload: Adding Hoot.mkv 
  autoload: Adding How Great Is Your Love (Special Stage).mp4 
  autoload: Adding I Got A Boy.mp4 
  autoload: Adding Into The New World (Ballad Version).mp4 
  autoload: Adding Into The New World + Beginning (KM Show Music Tank.mkv 
  autoload: Adding Into The New World (Dance Version).mp4 
  autoload: Adding Into The New World (Live 070816).mp4 
  autoload: Adding Into The New World (Live 070819).mp4 
  autoload: Adding Into The New World (Live 100825).mp4 
  autoload: Adding Into The New World.mkv 
  autoload: Adding Into The New World (Remix 070927).mkv 
  autoload: Adding Kissing You.mkv 
  autoload: Adding Lion Heart (Inkigayo 20150913).mkv 
  autoload: Adding Lion Heart.mkv 
  autoload: Adding Love & Girls.mp4 
  autoload: Adding Love & Peace Japan 3rd Tour.mp4 
  autoload: Adding Mr. Mr. (Live 140323).mkv 
  autoload: Adding Mr. Mr.mp4 
  autoload: Adding Mr. Taxi (Dance Ver).mp4 
  autoload: Adding Mr. Taxi + The Boys Live (111021).mp4 
  autoload: Adding My Oh My.mp4 
  autoload: Adding Oh! (In Colorful Outfit).mp4 
  autoload: Adding Oh!.mkv 
  autoload: Adding Over The Rainbow.mkv 
  autoload: Adding Paparazzi.mp4 
  autoload: Adding Party.mkv 
  autoload: Adding Party (Music Core 20150718).mkv 
  autoload: Adding Pattaya Music Festival (090321).avi 
  autoload: Adding Run Devil Run (3D).mp4 
  autoload: Adding Run Devil Run.mp4 
  autoload: Adding Samyang Ramyun Winter.mkv 
  autoload: Adding SeoHyun's Mom and Tiffany's Thank You Message.flv 
  autoload: Adding Sexy Dance.mkv 
  autoload: Adding Showcase Live in Tokyo.mkv 
  autoload: Adding Show! Show! Show! Live.mp4 
  autoload: Adding So Nyu Shi Dae.mp4 
  autoload: Adding SooYoung Dior.mkv 
  autoload: Adding Supernova.mp4 
  autoload: Adding Tell Me Your Wish @ Incheon Korean Music Wave.mkv 
  autoload: Adding Tell Me Your Wish.mkv 
  autoload: Adding Tell Me Your Wish @ Rooftop Heliport.mkv 
  autoload: Adding Tell Me Your Wish (SBS Inkigayo 090719).avi 
  autoload: Adding The Boys ComeBack Stage.mkv 
  autoload: Adding The Boys (English).mkv 
  autoload: Adding The Boys (Korean).mkv 
  autoload: Adding The Boys (Letterman).mp4 
  autoload: Adding The Boys Remix (MAMA 2011).mp4 
  autoload: Adding Time Machine.mp4 
  autoload: Adding Twinkle.mkv 
  autoload: Adding Visual Dreams.mp4 
  autoload: Adding Way to Go!.mp4 
  autoload: Adding You Think (Comeback Special 20150823).mkv 
   cplayer:  (+) Video --vid=1 (*) (h264 1920x1080 30.000fps)
   cplayer:  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
        vd: Using hardware decoding (nvdec-copy).
  ao/pulse: The --audio-stream-silence option is set. This will break certain player behavior.
   cplayer: AO: [pulse] 48000Hz stereo 2ch float
   cplayer: VO: [gpu] 1920x1080 nv12
  term-msg: MPV_VERSION=mpv 0.34.0-165-g712ef65e2a
  term-msg: INFO_VIDEO_WIDTH=1920
  term-msg: INFO_VIDEO_HEIGHT=1080
  term-msg: INFO_VIDEO_ASPECT=1.777778
  term-msg: INFO_VIDEO_FPS=30.000000
  term-msg: INFO_VIDEO_FORMAT=h264
  term-msg: INFO_VIDEO_CODEC=h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
  term-msg: INFO_DEMUX_ROTATION=
  term-msg: INFO_AUDIO_FORMAT=opus
  term-msg: INFO_AUDIO_CODEC=opus (Opus)
  term-msg: INFO_AUDIO_RATE=48000
  term-msg: INFO_AUDIO_NCH=2
  term-msg: INFO_LENGTH=258.521000
  term-msg: INFO_DEMUXER=mkv
  term-msg: INFO_SEEKABLE=yes
  term-msg: INFO_TITLES=
  term-msg: INFO_CHAPTERS=0
  term-msg: INFO_TRACKS_COUNT=2
  term-msg: METADATA_TITLE=
  term-msg: METADATA_ARTIST=
  term-msg: METADATA_ALBUM=
  term-msg: METADATA_GENRE=
  term-msg: METADATA_DATE=
  term-msg: METADATA_TRACK=
  term-msg: METADATA_COPYRIGHT=
  term-msg: INFO_MEDIA_TITLE=Divine.mkv
  term-msg: INFO_STREAM_PATH=/run/media/hanuman/Storage/NaturalGrounding/Girls' Generation/Divine.mkv
  term-msg: 
autoconvert: Converting nv12 -> yuv420p
osd/libass: fontselect: Using default font family: (mpv-osd-symbols, 400, 0) -> /usr/share/fonts/noto/NotoSans-Regular.ttf, 0, NotoSans-Regular
   cplayer: VO: [gpu] 1920x1080 yuv420p
```

**Comment by smplayer-dev** [comment]
I don't see any error in the log.
Try selecting another video output in preferences -> general -> video.

**Comment by mysteryx93** [comment]
select another video renderer doesn't help

With another video now I get some errors

```
/usr/bin/mpv --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-9bf48 --msg-level=ffmpeg/demuxer=error --video-rotate=no --no-fs --hwdec=no --sub-auto=fuzzy --vo=gpu, --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=94371857 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=110 --cache=auto --start=202 --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/home/hanuman/Pictures/smplayer_screenshots --audio-pitch-correction=yes --volume-max=110 --hr-seek-framedrop=no --profile=gpu-hq --gpu-api=vulkan --hwdec=auto-copy --vulkan-async-compute=yes --vulkan-async-transfer=yes --vulkan-queue-count=1 --autofit=85%x85% --dither=error-diffusion --deband=yes --deband-iterations=2 --deband-threshold=20 --deband-range=16 --scale=ewa_hanning --scale-radius=3.2383154841662362 --cscale=ewa_lanczossoft --dscale=mitchell --scale-antiring=0 --cscale-antiring=0 --correct-downscaling=yes --linear-downscaling=no --sigmoid-upscaling=yes --blend-subtitles=no --hdr-compute-peak=yes --tone-mapping=mobius --glsl-shaders-clr --fbo-format=rgba16f --glsl-shader=~/.config/mpv/shaders/FSRCNN_x2_r2_32-0-2.glsl --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} /run/media/hanuman/Storage/NaturalGrounding/AOA/Good Luck.mkv

  autoload: Prepending Get Out.mp4 
  autoload: Prepending Excuse Me.mkv 
  autoload: Prepending Elvis.mp4 
  autoload: Prepending Confused (Show Champion 20131023).mp4 
  autoload: Prepending Confused.mp4 
  autoload: Prepending 흔들려 혜정 직캠 (140607).mkv 
  autoload: Adding Heart Attack.webm 
  autoload: Adding I'm Jelly BABY.mkv 
  autoload: Adding Like a Cat (Dance Practice).mp4 
  autoload: Adding Like a Cat.mp4 
  autoload: Adding Like a Cat (Show Champion).mp4 
  autoload: Adding Miniskirt (Eye Contact Practice).mp4 
  autoload: Adding Miniskirt.mp4 
  autoload: Adding Miniskirt (Music Core 20140118).mp4 
  autoload: Adding Miniskirt (Show Champion 20140212).mp4 
  autoload: Adding MOYA.mp4 
  autoload: Adding MOYA (Show Champion 20130731).mp4 
  autoload: Adding Short Hair (Eye Contact Practice).mp4 
  autoload: Adding Short Hair.mp4 
  autoload: Adding Short Hair (Show Champion).mp4 
  autoload: Adding 「愛をちょうだい.mkv 
   cplayer:  (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
   cplayer:  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
        vd: Using hardware decoding (nvdec-copy).
  ao/pulse: The --audio-stream-silence option is set. This will break certain player behavior.
   cplayer: AO: [pulse] 48000Hz stereo 2ch float
   cplayer: VO: [gpu] 1920x1080 nv12
  term-msg: MPV_VERSION=mpv 0.34.0-165-g712ef65e2a
  term-msg: INFO_VIDEO_WIDTH=1920
  term-msg: INFO_VIDEO_HEIGHT=1080
  term-msg: INFO_VIDEO_ASPECT=1.777778
  term-msg: INFO_VIDEO_FPS=23.976025
  term-msg: INFO_VIDEO_FORMAT=h264
  term-msg: INFO_VIDEO_CODEC=h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
  term-msg: INFO_DEMUX_ROTATION=
  term-msg: INFO_AUDIO_FORMAT=opus
  term-msg: INFO_AUDIO_CODEC=opus (Opus)
  term-msg: INFO_AUDIO_RATE=48000
  term-msg: INFO_AUDIO_NCH=2
  term-msg: INFO_LENGTH=240.521000
  term-msg: INFO_DEMUXER=mkv
  term-msg: INFO_SEEKABLE=yes
  term-msg: INFO_TITLES=
  term-msg: INFO_CHAPTERS=0
  term-msg: INFO_TRACKS_COUNT=2
  term-msg: METADATA_TITLE=
  term-msg: METADATA_ARTIST=
  term-msg: METADATA_ALBUM=
  term-msg: METADATA_GENRE=
  term-msg: METADATA_DATE=
  term-msg: METADATA_TRACK=
  term-msg: METADATA_COPYRIGHT=
  term-msg: INFO_MEDIA_TITLE=Good Luck.mkv
  term-msg: INFO_STREAM_PATH=/run/media/hanuman/Storage/NaturalGrounding/AOA/Good Luck.mkv
  term-msg: 
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: Failed holding swapchain image for presentation
    vo/gpu: Failed presenting frame!
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: Failed holding swapchain image for presentation
    vo/gpu: Failed presenting frame!
vo/gpu/vulkan/libplacebo: vk->QueueSubmit(cmd->queue, 1, &sinfo, cmd->fence): VK_ERROR_DEVICE_LOST (../src/vulkan/command.c:373)
vo/gpu/vulkan/libplacebo: Failed holding swapchain image for presentation
    vo/gpu: Failed presenting frame!
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
vo/gpu/vulkan/libplacebo: Failed acquiring swapchain image: VK_NOT_READY
```
